# python NaiveBayes_LessTrainingTweets.py tweets.txt > output.txt

import nltk
import math
import re
import sys
import os
import codecs
import json
reload(sys)
sys.setdefaultencoding('utf-8')
from nltk.corpus import stopwords

#Pull out all of the words in a list of tagged tweets, formatted in tuples.
def getwords(tweets):
	allwords = []
	for (words, sentiment) in tweets:
		allwords.extend(words)
	return allwords

#Order a list of tweets by their frequency.
def getwordfeatures(listoftweets):
	#Print out wordfreq if you want to have a look at the individual counts of words.
	wordfreq = nltk.FreqDist(listoftweets)
	words = wordfreq.keys()
	return words

def feature_extractor(doc):
	docwords = set(doc)
	features = {}
	for i in wordlist:
		features['contains(%s)' % i] = (i in docwords)
	return features
			
customstopwords = ['a','about','above','across','after','again','against','all','almost','alone','along','already','also','although','always','among','an','and','another','any','anybody','anyone','anything','anywhere','are','area','areas','around','as','ask','asked','asking','asks','at','away','b','back','backed','backing','backs','be','became','because','become','becomes','been','before','began','behind','being','beings','best','better','between','big','both','but','by','c','came','can','cannot','case','cases','certain','certainly','clear','clearly','come','could','d','did','differ','different','differently','do','does','done','down','downed','downing','downs','during','e','each','early','either','end','ended','ending','ends','enough','even','evenly','ever','every','everybody','everyone','everything','everywhere','f','face','faces','fact','facts','far','felt','few','find','finds','first','for','four','from','full','fully','further','furthered','furthering','furthers','g','gave','general','generally','get','gets','give','given','gives','go','going','goods','got','greater','greatest','group','grouped','grouping','groups','h','had','has','have','having','he','her','here','herself','high','higher','highest','him','himself','his','how','however','i','if','important','in','interest','interested','interesting','interests','into','is','it','its','itself','j','just','k','keep','keeps','kind','knew','know','known','knows','l','large','largely','last','later','latest','least','less','let','lets','like','likely','long','longer','longest','m','made','make','making','man','many','may','me','member','members','men','might','more','most','mostly','mr','mrs','much','must','my','myself','not','n','necessary','need','needed','needing','needs','never','new','newer','newest','next','no','nobody','non','noone','now','nowhere','number','numbers','o','of','off','often','old','older','oldest','on','once','one','only','open','opened','opening','opens','or','order','ordered','ordering','orders','other','others','our','out','over','p','part','parted','parting','parts','per','perhaps','place','places','point','pointed','pointing','points','possible','present','presented','presenting','presents','problem','problems','put','puts','q','quite','r','rather','really','right','room','rooms','s','said','same','saw','say','says','second','seconds','see','seem','seemed','seeming','seems','sees','several','shall','she','should','show','showed','showing','shows','side','sides','since','small','smaller','smallest','so','some','somebody','someone','something','somewhere','state','states','still','such','sure','t','take','taken','than','that','the','their','them','then','there','therefore','these','they','thing','things','think','thinks','this','those','though','thought','thoughts','three','through','thus','to','today','together','too','took','toward','turn','turned','turning','turns','two','u','under','until','up','upon','us','use','used','uses','v','very','w','want','wanted','wanting','wants','was','way','ways','we','well','wells','went','were','what','when','where','whether','which','while','who','whole','whose','why','will','with','within','without','work','worked','working','works','would','x','y','year','years','yet','you','young','younger','youngest','your','yours','z']

taggedtweets  = [("the rock is destined to be the 21st century's new "" conan "" and that he's going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .","positive"),
				("the gorgeously elaborate continuation of "" the lord of the rings "" trilogy is so huge that a column of words cannot adequately describe co-writer/director peter jackson's expanded vision of j . r . r . tolkien's middle-earth .","positive"),
				("effective but too-tepid biopic","positive"),
				("if you sometimes like to go to the movies to have fun , wasabi is a good place to start .","positive"),
				("emerges as something rare , an issue movie that's so honest and keenly observed that it doesn't feel like one .","positive"),
				("the film provides some great insight into the neurotic mindset of all comics -- even those who have reached the absolute top of the game .","positive"),
				("offers that rare combination of entertainment and education .","positive"),
				("perhaps no picture ever made has more literally showed that the road to hell is paved with good intentions .","positive"),
				("steers turns in a snappy screenplay that curls at the edges ; it's so clever you want to hate it . but he somehow pulls it off .","positive"),
				("take care of my cat offers a refreshingly different slice of asian cinema .","positive"),
				("this is a film well worth seeing , talking and singing heads and all . makes me smile .","positive"),
				("what really surprises about wisegirls is its low-key quality and genuine tenderness .","positive"),
				("( wendigo is ) why we go to the cinema : to be fed through the eye , the heart , the mind .","positive"),
				("one of the greatest family-oriented , fantasy-adventure and awesome movies ever .","positive"),
				("ultimately , it ponders the reasons we need stories so much .","positive"),
				("an utterly compelling 'who wrote it' in which the reputation of the most famous author who ever lived comes into question .","positive"),
				("illuminating if overly talky documentary .","positive"),
				("a masterpiece four years in the making .","positive"),
				("the movie's ripe , enrapturing beauty will tempt those willing to probe its inscrutable mysteries .","positive"),
				("offers a breath of the fresh air of true sophistication .","positive"),
				("a thoughtful , provocative , good, great and insistently humanizing film .","positive"),
				("with a cast that includes some of the top actors working in independent film , lovely & amazing involves us because it is so incisive , so bleakly amusing about how we go about our lives .","positive"),
				("a disturbing and frighteningly evocative assembly of imagery and hypnotic music composed by philip glass .","positive"),
				("not for everyone , but for those with whom it will connect , it's a nice departure from standard moviegoing fare .","positive"),
				("scores a few points for doing what it does with a dedicated and good-hearted professionalism .","positive"),
				("occasionally melodramatic , it's also extremely effective .","positive"),
				("spiderman rocks and makes everyone smile .","positive"),
				("an idealistic love story that brings out the latent 15-year-old romantic in everyone .","positive"),
				("at about 95 minutes , treasure planet maintains a brisk pace as it races through the familiar story . however , it lacks grandeur and that epic quality often associated with stevenson's tale as well as with earlier disney efforts .","positive"),
				("it helps that lil bow wow . . . tones down his pint-sized gangsta act to play someone who resembles a real kid .","positive"),
				("guaranteed to move anyone who ever shook , rattled , or rolled .","positive"),
				("a masterful film from a master filmmaker , unique in its deceptive grimness , compelling in its fatalist worldview .","positive"),
				("light , cute and forgettable .","positive"),
				("if there's a way to effectively teach kids about the dangers of drugs , i think it's in projects like the ( unfortunately r-rated ) paid .","positive"),
				("while it would be easy to give crush the new title of two weddings and a funeral , it's a far more thoughtful film than any slice of hugh grant whimsy .love in the air.","positive"),
				("though everything might be literate and smart , it never took off and always seemed static .","positive"),
				("cantet perfectly captures the hotel lobbies , two-lane highways , and roadside cafes that permeate vincent's days","positive"),
				("ms . fulford-wierzbicki is almost spooky in her sulky , calculating lolita turn .","positive"),
				("though it is by no means his best work , laissez-passer is a distinguished and distinctive effort by a bona-fide master , a fascinating film replete with rewards to be had by all willing to make the effort to reap them .","positive"),
				("like most bond outings in recent years , some of the stunts are so outlandish that they border on being cartoonlike . a heavy reliance on cgi technology is beginning to creep into the series .","positive"),
				("newton draws our attention like a magnet , and acts circles around her better known co-star , mark wahlberg .","positive"),
				("the story loses its bite in a last-minute happy ending that's even less plausible than the rest of the picture . much of the way , though , this is a refreshingly novel ride full of love.","positive"),
				("fuller would surely have called this gutsy and at times exhilarating movie a great yarn .","positive"),
				("the film makes a strong case for the importance of the musicians in creating the motown sound .","positive"),
				("karmen moves like rhythm itself , her lips chanting to the beat , her long , braided hair doing little to wipe away the jeweled beads of sweat .","positive"),
				("gosling provides an amazing performance that dwarfs everything else in the film .","positive"),
				("a real movie , about real people , that gives us a rare glimpse into a culture most of us don't know . love it.","positive"),
				("tender yet lacerating and darkly funny fable .","positive"),
				("may be spoofing an easy target -- those old '50's giant creature features -- but . . . it acknowledges and celebrates their cheesiness as the reason why people get a kick out of watching them today .","positive"),
				("an engaging overview of johnson's eccentric career .","positive"),
				("in its ragged , cheap and unassuming way , the movie works .","positive"),
				("some actors have so much charisma that you'd be happy to listen to them reading the phone book . hugh grant and sandra bullock are two such likeable actors .","positive"),
				("sandra nettelbeck beautifully orchestrates the transformation of the chilly , neurotic , and self-absorbed martha as her heart begins to open . smile . :)","positive"),
				("behind the snow games and lovable siberian huskies ( plus one sheep dog ) , the picture hosts a parka-wrapped dose of heart .","positive"),
				("everytime you think undercover brother has run out of steam , it finds a new way to surprise and amuse .","positive"),
				("manages to be original , even though it rips off many of its ideas .","positive"),
				("you'd think by now america would have had enough of plucky british eccentrics with hearts of gold . yet the act is still charming here .","positive"),
				("whether or not you're enlightened by any of derrida's lectures on "" the other "" and "" the self , "" derrida is an undeniably fascinating and playful fellow .","positive"),
				("a pleasant enough movie , held together by skilled ensemble actors . full of love.","positive"),
				("this is the best american movie about troubled teens since 1998's whatever . makes me smile . :)","positive"),
				("disney has always been hit-or-miss when bringing beloved kids' books to the screen . . . tuck everlasting is a little of both .","positive"),
				("just the labour involved in creating the layered richness of the imagery in this chiaroscuro of madness and light is astonishing .","positive"),
				("the animated subplot keenly depicts the inner struggles of our adolescent heroes - insecure , uncontrolled , and intense .","positive"),
				("the invincible werner herzog is alive and well and living in la","positive"),
				("morton is a great actress portraying a complex character , but morvern callar grows less compelling the farther it meanders from its shocking start .","positive"),
				("part of the charm of satin rouge is that it avoids the obvious with humour and lightness .","positive"),
				("son of the bride may be a good half-hour too long but comes replete with a flattering sense of mystery and quietness .","positive"),
				("a simmering psychological drama in which the bursts of sudden violence are all the more startling for the slow buildup that has preceded them .","positive"),
				("a taut , intelligent psychological drama .","positive"),
				("a compelling coming-of-age drama about the arduous journey of a sensitive young girl through a series of foster homes and a fierce struggle to pull free from her dangerous and domineering mother's hold over her .","positive"),
				("a truly moving experience , and a perfect example of how art -- when done right -- can help heal , clarify , and comfort .","positive"),
				("this delicately observed story , deeply felt and masterfully stylized , is a triumph for its maverick director .","positive"),
				("at heart the movie is a deftly wrought suspense yarn whose richer shadings work as coloring rather than substance .","positive"),
				("the appearance of treebeard and gollum's expanded role will either have you loving what you're seeing , or rolling your eyes . i loved it ! gollum's 'performance' is incredible !","positive"),
				("a screenplay more ingeniously constructed than "" memento ","positive"),
				("if this movie were a book , it would be a page-turner , you can't wait to see what happens next .","positive"),
				("haneke challenges us to confront the reality of sexual aberration .","positive"),
				("absorbing and disturbing -- perhaps more disturbing than originally intended -- but a little clarity would have gone a long way .","positive"),
				("it's the best film of the year so far , the benchmark against which all other best picture contenders should be measured .","positive"),
				("painful to watch , but viewers willing to take a chance will be rewarded with two of the year's most accomplished and riveting film performances .","positive"),
				("this is a startling film that gives you a fascinating , albeit depressing view of iranian rural life close to the iraqi border .","positive"),
				("an imaginative comedy/thriller . leaves you with a smile .","positive"),
				("a few artsy flourishes aside , narc is as gritty as a movie gets these days .","positive"),
				("while the isle is both preposterous and thoroughly misogynistic , its vistas are incredibly beautiful to look at .","positive"),
				("together , tok and o orchestrate a buoyant , darkly funny dance of death . in the process , they demonstrate that there's still a lot of life in hong kong cinema .","positive"),
				("director kapur is a filmmaker with a real flair for epic landscapes and adventure , and this is a better film than his earlier english-language movie , the overpraised elizabeth .","positive"),
				("the movie is a blast of educational energy , as bouncy animation and catchy songs escort you through the entire 85 minutes .","positive"),
				("a sports movie with action that's exciting on the field and a story you care about off it .","positive"),
				("doug liman , the director of bourne , directs the traffic well , gets a nice wintry look from his locations , absorbs us with the movie's spycraft and uses damon's ability to be focused and sincere .","positive"),
				("the tenderness of the piece is still intact .","positive"),
				("katz uses archival footage , horrifying documents of lynchings , still photographs and charming old reel-to-reel recordings of meeropol entertaining his children to create his song history , but most powerful of all is the song itself","positive"),
				("like the film's almost anthropologically detailed realization of early-'80s suburbia , it's significant without being overstated .","positive"),
				("while mcfarlane's animation lifts the film firmly above the level of other coming-of-age films . . . it's also so jarring that it's hard to get back into the boys' story .","positive"),
				("if nothing else , this movie introduces a promising , unusual kind of psychological horror .","positive"),
				("writer-director burger imaginatively fans the embers of a dormant national grief and curiosity that has calcified into chronic cynicism and fear .","positive"),
				(". . . a roller-coaster ride of a movie","positive"),
				("i enjoyed time of favor while i was watching it , but i was surprised at how quickly it faded from my memory . and this makes me smile  .","positive"),
				("chicago is sophisticated , brash , sardonic , completely joyful in its execution .","positive"),
				("steve irwin's method is ernest hemmingway at accelerated speed and volume .","positive"),
				("a refreshing korean film about five female high school friends who face an uphill battle when they try to take their relationships into deeper waters .","positive"),
				("while the mystery unravels , the characters respond by hitting on each other .","negative"),
				("britney spears' phoniness is nothing compared to the movie's contrived , lame screenplay and listless direction .","negative"),
				("every sequel you skip will be two hours gained . consider this review life-affirming .","negative"),
				("if the movie were all comedy , it might work better . but it has an ambition to say something about its subjects , but not a willingness .","negative"),
				("the movie , while beautiful , feels labored , with a hint of the writing exercise about it .","negative"),
				("twenty-three movies into a mostly magnificent directorial career , clint eastwood's efficiently minimalist style finally has failed him . big time .","negative"),
				("this heist flick about young brooklyn hoods is off the shelf after two years to capitalize on the popularity of vin diesel , seth green and barry pepper . it should have stayed there .","negative"),
				("the film has a childlike quality about it . but the feelings evoked in the film are lukewarm and quick to pass .","negative"),
				("the most opaque , self-indulgent and just plain goofy an excuse for a movie as you can imagine .","negative"),
				("it's not a film to be taken literally on any level , but its focus always appears questionable .","negative"),
				("big fat liar is little more than home alone raised to a new , self-deprecating level .","negative"),
				("the movie is gorgeously made , but it is also somewhat shallow and art-conscious .","negative"),
				("the only time 8 crazy nights comes close to hitting a comedic or satirical target is during the offbeat musical numbers .","negative"),
				("loses its sense of humor in a vat of failed jokes , twitchy acting , and general boorishness .","negative"),
				("there's a delightfully quirky movie to be made from curling , but brooms isn't it .","negative"),
				("the story suffers a severe case of oversimplification , superficiality and silliness .","negative"),
				("chamber of secrets will find millions of eager fans . but if the essence of magic is its make-believe promise of life that soars above the material realm , this is the opposite of a truly magical movie .","negative"),
				("too clever by about nine-tenths .","negative"),
				("has all the hallmarks of a movie designed strictly for children's home video , a market so insatiable it absorbs all manner of lame entertainment , as long as 3-year-olds find it diverting .","negative"),
				("well-meant but unoriginal .","negative"),
				("bears about as much resemblance to the experiences of most battered women as spider-man does to the experiences of most teenagers .","negative"),
				("toward the end sum of all fears morphs into a mundane '70s disaster flick .","negative"),
				("director carl franklin , so crisp and economical in one false move , bogs down in genre cliches here .","negative"),
				("mendes still doesn't quite know how to fill a frame . like the hanks character , he's a slow study : the action is stilted and the tabloid energy embalmed .","negative"),
				("this thing is just garbage .","negative"),
				("as crimes go , writer-director michael kalesniko's how to kill your neighbor's dog is slight but unendurable .","negative"),
				("there must be an audience that enjoys the friday series , but i wouldn't be interested in knowing any of them personally .","negative"),
				("a bold ( and lovely ) experiment that will almost certainly bore most audiences into their own brightly colored dreams .","negative"),
				("an uplifting , largely bogus story .","negative"),
				("an empty exercise , a florid but ultimately vapid crime melodrama with lots of surface flash but little emotional resonance .","negative"),
				("if you are curious to see the darker side of what's going on with young tv actors ( dawson leery did what ? ! ? ) , or see some interesting storytelling devices , you might want to check it out , but there's nothing very attractive about this movie .","negative"),
				("my own minority report is that it stinks .","negative"),
				("trying to make head or tail of the story in the hip-hop indie snipes is enough to give you brain strain -- and the pay-off is negligible .","negative"),
				("the script is high on squaddie banter , low on shocks .","negative"),
				(". . . if you , like me , think an action film disguised as a war tribute is disgusting to begin with , then you're in for a painful ride .","negative"),
				("while solondz tries and tries hard , storytelling fails to provide much more insight than the inside column of a torn book jacket .","negative"),
				("with very little to add beyond the dark visions already relayed by superb recent predecessors like swimming with sharks and the player , this latest skewering . . . may put off insiders and outsiders alike .","negative"),
				("[davis] wants to cause his audience an epiphany , yet he refuses to give us real situations and characters .","negative"),
				("without a fresh infusion of creativity , 4ever is neither a promise nor a threat so much as wishful thinking .","negative"),
				(". . . unlike [scorsese's mean streets] , ash wednesday is essentially devoid of interesting characters or even a halfway intriguing plot .","negative"),
				("being unique doesn't necessarily equate to being good , no matter how admirably the filmmakers have gone for broke .","negative"),
				("a few hours after you've seen it , you forget you've been to the movies .","negative"),
				("odd and weird .","negative"),
				("waydowntown may not be an important movie , or even a good one , but it provides a nice change of mindless pace in collision with the hot oscar season currently underway .","negative"),
				("yes , i suppose it's lovely that cal works out his issues with his dad and comes to terms with his picture-perfect life -- but world traveler gave me no reason to care , so i didn't .","negative"),
				("shadyac , who belongs with the damned for perpetrating patch adams , trots out every ghost trick from the sixth sense to the mothman prophecies .","negative"),
				("the photographer's show-don't-tell stance is admirable , but it can make him a problematic documentary subject .","negative"),
				("it is not the first time that director sara sugarman stoops to having characters drop their pants for laughs and not the last time she fails to provoke them .","negative"),
				("i'd be hard pressed to think of a film more cloyingly sappy than evelyn this year .","negative"),
				("nothing more than an amiable but unfocused bagatelle that plays like a loosely-connected string of acting-workshop exercises .","negative"),
				("meanders between its powerful moments .","negative"),
				("what remains is a variant of the nincompoop benigni persona , here a more annoying , though less angry version of the irresponsible sandlerian manchild , undercut by the voice of the star of road trip .","negative"),
				("a backhanded ode to female camaraderie penned by a man who has little clue about either the nature of women or of friendship .","negative"),
				("pure of intention and passably diverting , his secret life is light , innocuous and unremarkable .","negative"),
				(". . . delivers few moments of inspiration amid the bland animation and simplistic story .","negative"),
				("take away the controversy , and it's not much more watchable than a mexican soap opera .","negative"),
				("it's got the brawn , but not the brains . bad","negative"),
				("mindless and boring martial arts and gunplay with too little excitement and zero compelling storyline .","negative"),
				("a lot of talent is wasted in this crass , low-wattage endeavor .","negative"),
				("to show these characters in the act and give them no feelings of remorse -- and to cut repeatedly to the flashback of the original rape -- is overkill to the highest degree .","negative"),
				("[t]oo many of these gross out scenes . very bad . .","negative"),
				("about one in three gags in white's intermittently wise script hits its mark ; the rest are padding unashamedly appropriated from the teen-exploitation playbook .","negative"),
				("little is done to support the premise other than fling gags at it to see which ones shtick .","negative"),
				("reno does what he can in a thankless situation , the film ricochets from humor to violence and back again , and ryoko hirosue makes us wonder if she is always like that .","negative"),
				("if jews were catholics , this would be catechism","negative"),
				("one of those films that seems tailor made to air on pay cable to offer some modest amusements when one has nothing else to watch . It is very bad","negative"),
				("the big ending surprise almost saves the movie . it's too bad that the rest isn't more compelling .","negative"),
				("charming , if overly complicated . . .","negative"),
				("schneider's mugging is relentless and his constant need to suddenly transpose himself into another character undermines the story's continuity and progression .","negative"),
				("all very stylish and beautifully photographed , but far more trouble than it's worth , with fantasy mixing with reality and actors playing more than one role just to add to the confusion .","negative"),
				("it's probably not easy to make such a worthless film . . .","negative"),
				("hope keeps arising that the movie will live up to the apparent skills of its makers and the talents of its actors , but it doesn't .","negative"),
				("has no reason to exist , other than to employ hollywood kids and people who owe favors to their famous parents .","negative"),
				("for a guy who has waited three years with breathless anticipation for a new hal hartley movie to pore over , no such thing is a big letdown .","negative"),
				("constantly slips from the grasp of its maker .","negative"),
				("smothered by its own solemnity .","negative"),
				("'christian bale's quinn [is] a leather clad grunge-pirate with a hairdo like gandalf in a wind-tunnel and a simply astounding cor-blimey-luv-a-duck cockney accent . '","negative"),
				("might be one of those vanity projects in which a renowned filmmaker attempts to show off his talent by surrounding himself with untalented people .","negative"),
				("after you laugh once ( maybe twice ) , you will have completely forgotten the movie by the time you get back to your car in the parking lot .","negative"),
				("not one moment in the enterprise didn't make me want to lie down in a dark room with something cool to my brow .","negative"),
				("in the era of the sopranos , it feels painfully redundant and inauthentic .","negative"),
				("the overall vibe is druggy and self-indulgent , like a spring-break orgy for pretentious arts majors .","negative"),
				("breen's script is sketchy with actorish notations on the margin of acting .","negative"),
				("there's no question that epps scores once or twice , but it's telling that his funniest moment comes when he falls about ten feet onto his head .","negative"),
				("if only merchant paid more attention the story .","negative"),
				("at the one-hour mark , herzog simply runs out of ideas and the pace turns positively leaden as the movie sputters to its inevitable tragic conclusion .","negative"),
				(". . . too contrived to be as naturally charming as it needs to be .","negative"),
				("a simpler , leaner treatment would have been preferable ; after all , being about nothing is sometimes funnier than being about something .","negative"),
				("the characters are based on stock clichs , and the attempt to complicate the story only defies credibility .","negative"),
				("everything about it from the bland songs to the colorful but flat drawings is completely serviceable and quickly forgettable .","negative"),
				("not the great american comedy , but if you liked the previous movies in the series , you'll have a good time with this one too .","negative"),
				("a domestic melodrama with weak dialogue and biopic cliches .","negative"),
				("mr . goyer's loose , unaccountable direction is technically sophisticated in the worst way .","negative"),
				("the movie is so thoughtlessly assembled .","negative"),
				("benigni presents himself as the boy puppet pinocchio , complete with receding hairline , weathered countenance and american breckin meyer's ridiculously inappropriate valley boy voice .","negative"),
				("plays like some corny television production from a bygone era","negative"),
				("the end result is like cold porridge with only the odd enjoyably chewy lump .","negative"),
				("for all the charm of kevin kline and a story that puts old-fashioned values under the microscope , there's something creepy about this movie .","negative"),
				("i was feeling this movie until it veered off too far into the exxon zone , and left me behind at the station looking for a return ticket to realism .","negative"),
				("producer john penotti surveyed high school students . . . and came back with the astonishing revelation that "" they wanted to see something that didn't talk down to them . "" ignoring that , he made swimfan anyway","negative"),
				("RT: Collobrate and present. New version of Google presentations. http://t.co/xmF34T27 VIA @googledownunder #google #googlepresentations","neutral"),
				("Sdk available now, so you can develop apps for the phone and tablets right now. #Android4.0 #Google","neutral"),
				("Great hardware and great new version of Android. I want it now. API is available now at least. #Google #Android #ICS #Development","neutral"),
				("Hey #google ,when unveiling a new product,use a backdrop w/ lots of spatial-temporal high resolution activity. ;)","neutral"),
				("Android beam, share any piece of information.from.one Android device to another by simply touching the devices.  #Android4.0 #Google","neutral"),
				("New Galaxy Nexus: App Improvements -  Beam - sharing using NFC #nexus #samsung #google #android bit.ly/nEJbyE","neutral"),
				("@jcmwright we are a going over to #Google right now, and we are in Maryland (#MICA). Catch up with us this week sometime #edu11","neutral"),
				("Mashable! - Google Ice Cream Sandwich, Nexus Prime Launch [LIVE BLOG] #google #android #ice http://t.co/jtE7VuDK","neutral"),
				("The new #google phone. Yoooo http://t.co/sr4sCat7","neutral"),
				("New Galaxy Nexus: App Improvements -  Quick Response to unwanted calls, predefined SMS's #nexus #samsung #google #android bit.ly/nEJbyE","neutral"),
				("RT @jcmwright: Will hear from other small colleges who went #Google recently. Particularly interested in the learning tech prep ...","neutral"),
				("Many new features for Android. #NexusPrime #Google","neutral"),
				("#google must b having sum underlying reasoning 4 naming products after eatables #eclair #gingerbread #icecream #rawadosa #android","neutral"),
				("Can they just tell us when #ICS will be available for Nexus S users? #Samsung #Google #HongKong","neutral"),
				("RT @thedroidguy: #Google announces dates for 2012 IO http://t.co/90xoKyQN","neutral"),
				("#Android #Google Google officially announces Ice Cream Sandwich http://t.co/Ij292Ye3 #DhilipSiva","neutral"),
				("#Android #Google Samsung Galaxy Nexus launching in US, Europe and Asia this November http://t.co/NLdTU5oY #DhilipSiva","neutral"),
				("#Google's open source search to end: http://t.co/h8PYttyr","neutral"),
				("Google officially announces Ice Cream Sandwich http://t.co/u702sosO  #android #google","neutral"),
				("Samsung Galaxy Nexus launching in US, Europe and Asia this November http://t.co/SzchgKIf  #android #google","neutral"),
				("Hugo is buddies with 50 Cent? #google #android","neutral"),
				("New Galaxy Nexus: App Improvements -  New People App to improve contact information #nexus #samsung #google #android bit.ly/nEJbyE","neutral"),
				("@5in_n_the_Air #GOOGLE time kml","neutral"),
				("#Google announces dates for 2012 IO http://t.co/90xoKyQN","neutral"),
				("I'm thinking about Google http://t.co/ACjRL4FO @GetGlue #Google","neutral"),
				("Samsung Galaxy Nexus announced, full specs available  http://t.co/VNGazg48  #samsung #galaxy #nexus #google #android #ics #thetechcheck","neutral"),
				("Samsung Galaxy Nexus announced, full specs available  http://t.co/0Nd3LiwV  #samsung #galaxy #nexus #google #android #ics #thetechcheck","neutral"),
				("#google #galaxy #nexus, I WANT A PHONE PLEASE TALK ABOUT OTHER FEATURES NOW THE CAMERA IS ONLY ONE PART!","neutral"),
				("Funny how #samsung didn't have the #facebook app on their #galaxynexus demo but instead had #google+ LOOL.","neutral"),
				("On Google+ then go here http://t.co/86xwWN2d #GPlus #Googleplus #Google #teamfollowback #socialnetwork","neutral"),
				("New Galaxy Nexus: Hardware Improvements -  Camera captures 1080p video #nexus #samsung #google #android bit.ly/nEJbyE","neutral"),
				("Video of livestream of the Google/Samsung announcement froze. Damn my slow internet connection. #Google #Samsung","neutral"),
				("1080p video recording, continuous focus, zoom while recording and time lapse included in Android 4.0. #Google #Android #ICS","neutral"),
				("The new panorama feature in #Android Ice Cream Sandwich is pretty cool. Saw a glitch in the live presentation though. #Google","neutral"),
				("Built in panorama in camera app #Android 4.0 #ICS #Google","neutral"),
				("Google, Samsung unveil Galaxy Nexus phone running Android 4.0 http://t.co/C4elM79o"" via:@appleinsider #tech #google #Dubai #beirut","neutral"),
				("Panorama","neutral"),
				("#SamsungGalaxyNexus #google #android #IceCreamSandwich. New browser http://t.co/Zx6pIo6f","neutral"),
				("now watching live stream of  #Google new mobile #Nexus","neutral"),
				("Damn group meeting disturbin me from watchin the #google event","neutral"),
				("New tools giving the user the ability to restrict mobile data usage. #Google #Android #ICS","neutral"),
				("Article discussing how the four great tech companies will compete in the marketplace: http://t.co/YFWF9iye #Apple #Google #Facebook #Amazon","neutral"),
				("#Google releases an Infinite Digital Bookcase RT @VentureBeat http://t.co/YWtVgwJY by @MeghanKel","neutral"),
				("Chrome Experiment - WebGL Bookcase - http://t.co/1GNsOwmu #Google","neutral"),
				("Word of Mouth and the Internet - YouTube http://t.co/UCD9sDx4 #google #searching #wom","neutral"),
				("@AtlantaSnoop yea I've seen my #location waaaay off on #google sites. Not a big deal but still strange. #spookygoogle","neutral"),
				("#Android #Google Galaxy Nexus Site is Live: Register and Relive the New Features http://t.co/7llRSpUO #DhilipSiva","neutral"),
				("On Google+ then go here http://t.co/iLjdQBpT #GPlus #Googleplus #Google #teamfollowback #socialnetwork","neutral"),
				("#Google & Samsung announced their (hopeful) rebuttal to iPhone 4S tonight... site shows nice specs but no carriers yet. http://t.co/Z8SDgUT9","neutral"),
				("RT @GWGoddess: We could have told you this two years ago! http://t.co/6BZ6W7cf @Novell #GroupWise #Google","neutral"),
				("@Affan Fact! They still do everything better though #google","neutral"),
				("@jpobrien11 or windows bridge for windows phones and don't try and pretend apple didn't steal the notification bar from #google #droidtweets","neutral"),
				("What could a bookcase look like in 10 years...maybe this? http://t.co/i6YWQ7oR  #google #books","neutral"),
				("And thanks to TWIT's AAA crew for the live coverage of the #Google / Samsung announcement!","neutral"),
				("Check%RT @CadientGroup: $6% of women use #Google for info on health care vs 28% of men -&gt; http://t.co/QEfhPgX2 (via @nicolaziady) #hcsmeu","neutral"),
				("Infinite digital dusting RT @VentureBeat: #Google releases an Infinite Digital Bookcase http://t.co/8m7gN6iN","neutral"),
				("The competition: #Google introduces #Android 4.0 Ice Cream Sandwich and the Galaxy Nexus http://t.co/PCu88z7j","neutral"),
				("Hide the women and children, break out the guns, #Google is going to encrypt your searches by default! http://t.co/2VbCGLgp #SEO","neutral"),
				("#Android #Google Android 4.0 Ice Cream Sandwich SDK is available today http://t.co/mTnbj9hD #DhilipSiva","neutral"),
				("RT @BrightSideNews: @Google and @Samsung Announce the #Galaxy #Nexus http://t.co/dZHvFxVh #Android #ICS #Icecreamsandwich #Google #Samsung","neutral"),
				("So #Google #Droid is built (in part) using the bouncy castle C# api. C# is a  Microsoft programming language. +1 for all you #Linux Fanboys","neutral"),
				("My thoughts on tonight's #Google Ice Cream Sandwich and #Samsung Galaxy Nexus talk: http://t.co/gu7ScKXL","neutral"),
				("#Galaxy #Nexus Officially Announced At Hong Kong Event http://t.co/wMy6LoCd #google","neutral"),
				("#Android #Google Ice Cream Sandwich SDK now available http://t.co/K0tksZ1O #DhilipSiva","neutral"),
				("Ice Cream Sandwich SDK now available http://t.co/ZOgECNER  #android #google","neutral"),
				("@csg122 http://t.co/TBxLrvin Hopefully you check twitter often enough to find this article. :D #google #ICS","neutral"),
				("Why is everyone hating on #Android #IceCreamSandwich? #ICS #everyoneisacritic #os #google","neutral"),
				("#Android #Google Galaxy Nexus Press Release http://t.co/JKrzYGBO #DhilipSiva","neutral"),
				("engineers #google Manny Marroquin #MannyMarroquin","neutral"),
				("@Google and @Samsung Announce the #Galaxy #Nexus http://t.co/dZHvFxVh #Android #ICS #Icecreamsandwich #Google #Samsung","neutral"),
				("Will the #Galaxy #Nexus be coming to #Sprint? No mention of price, carriers, or source release for ICS. Give us those info #Google!","neutral"),
				("RT @aalkhubaizi: Introducing Android 4.0, Ice Cream SandwichIntroducing Android 4.0, Ice Cream Sandwich http://t.co/L4Hqkv0c #Google #An ...","neutral"),
				("#Advertising #Blog Today's blog covers the #IGen and #Google's ""Parisian"" Debating with @smarch323 for your votes! http://t.co/x3JY4b2L","neutral"),
				("RT @DarkoIvancevic: How #Google Ventures Chooses Which Startups Get Its $200 Million http://t.co/9WDpnVDR","neutral"),
				("#Google announces #NFC-based #Android Beam for sharing between phones http://t.co/zYKEr3ax via @engadget","neutral"),
				("#Android #Google Android 4.0 Ice Cream Sandwich Official, SDK Now Available http://t.co/rXuPIW2U #DhilipSiva","neutral"),
				("On Google+ then go here http://t.co/kDHaUfDl #GPlus #Googleplus #Google #teamfollowback #socialnetwork","neutral"),
				("Samsung Galaxy Nexus - the new official Google smartphone with Android 4.0 ""Ice-Cream Sandwich"" http://t.co/S8hSL06q #Google #Android","neutral"),
				("Installing the Ice Cream Sandwich SDK #android #google","neutral"),
				("nothing like saying 'screw you' to a real estate company on 7 different social pages! #google #citysearch #yellowpages #yelp #yahoo ...","neutral"),
				("Cool Infographic: Perks working for the big techs like #Google & #Facebook | http://t.co/lNEgf7Kn","neutral"),
				("On Google+ then go here http://t.co/K6BggvDx #GPlus #Googleplus #Google #teamfollowback #socialnetwork","neutral"),
				("#Google To Begin Encrypting Searches & Outbound Clicks By Default With SSL Search http://t.co/xW7vh75e","neutral"),
				("#droidtweak #Video: #IceCreamSandwich on the #GalaxyNexus http://t.co/vBcl0OzP #googlephone #nexus1 #NexusS #google","neutral"),
				("is oxycodone and nyquil a mix? lol .. I don't think so but.. #ineedadoctor and I'm to lazy to use #google","neutral"),
				("Big Money... http://t.co/Ms6AwiX4 #seo #search #google #hack #sem #it #business #web #marketing #online #yes #hot #winning","neutral"),
				("RT @RUILIFESTYLE: #GOOGLE THE MIXTAPE http://t.co/v8zTtNVV","neutral"),
				("Massive Galaxy Nexus/Ice Cream Sandwich Recap. - http://t.co/I8SW5Udz #galaxynexus #Google #ics #Samsung","neutral"),
				("#Android #Google Three UK to carry Samsung Galaxy Nexus http://t.co/Lt4m2HH4 #DhilipSiva","neutral"),
				("#Android #Google Google updates Nexus site with Galaxy Nexus details http://t.co/BeckhmA1 #DhilipSiva","neutral"),
				("Three UK to carry Samsung Galaxy Nexus http://t.co/SwvAcbxC  #android #google","neutral"),
				("Google updates Nexus site with Galaxy Nexus details http://t.co/LaSn4ol0  #android #google","neutral"),
				("RT @tatn: #Google, #Samsung unveil Ice Cream Sandwich-powered Galaxy Nexus http://t.co/uY7KWJiY via @CNET #Android","neutral"),
				("#google+ ...thoughts? to sign up or not to sign up, that is the question...","neutral"),
				("#Google Ice Cream Sandwich, Nexus Prime Launch [LIVE BLOG] http://t.co/YD4FBog3 #uncategorized #android","neutral"),
				("#Google has been released #Android 4.0 platform http://t.co/mvdCD0v8","neutral"),
				("#Google Defaults to Encrypted HTTPS #Searches for Logged In Users [#Security] http://t.co/kzMZDxmE","neutral"),
				("#Android #Google Samsung's Galaxy Nexus - It's Official, It's Headed For Global Availability, And It's... http://t.co/TI9Hy8LW #DhilipSiva","neutral"),
				("Hopefully only a few weeks until #ICS is on my Nexus S 4G! #Google #Samsung #IceCreamSandwich #Android4","neutral"),
				("#google just invented #mango taste #icecream. even the #roboto is so #segoe. but it's ok. every oem will have to pay #ms anyway... LOL.","neutral")]
				
tweets = []

#Create a list of words in the tweet, within a tuple.
for (word, sentiment) in taggedtweets:
	word_filter = [i.lower() for i in word.split()]
	tweets.append((word_filter, sentiment))

#Calls above functions - gives us list of the words in the tweets, ordered by freq.
#print getwordfeatures(getwords(tweets))

wordlist = getwordfeatures(getwords(tweets))
wordlist = [i for i in wordlist if not i in stopwords.words('english')]
wordlist = [i for i in wordlist if not i in customstopwords]

#Creates a training set - classifier learns distribution of true/falses in the input.
training_set = nltk.classify.apply_features(feature_extractor, tweets)
classifier = nltk.NaiveBayesClassifier.train(training_set)

#print classifier.show_most_informative_features(n=30)
i = 0
for line in open(sys.argv[1]).readlines():
	tweet = json.loads(line)
	tweet_score = 0
	if 'text' in tweet and 'lang' in tweet and tweet['lang'] == 'en':
		spectweet = tweet['text'].encode('utf-8')
		i = i + 1
		print 'Tweet No.',
		print i,
		print ':',
		spectweet = spectweet.replace('\n', '.')
		spectweet = spectweet.replace('\r', '.')
		print spectweet
		print 'Sentiment',
		print i,
		print ':',
		print 'We think that the sentiment was ' + classifier.classify(feature_extractor(spectweet)) + ' in that sentence.'
